### ISSUE TITLE
mvn clean test fails

### ISSUE THREAD

**Issue by kcore** [gauravs-JavaDeveloper/MatrixOperations#1]
`[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   MatrixRestControllerTest.TestGetLongestSubMatrixWithEmptySet:66 expected:<[{Please provide valid matrix of integers}]> but was:<[Matrix should not be Empty]>
[INFO] 
[ERROR] Tests run: 13, Failures: 1, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10.435 s
[INFO] Finished at: 2019-05-09T16:03:36+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.1:test (default-test) on project MatrixProcessorApp: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/kcore/Workspace/java/playground/gauravs/MatrixOperations/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException`

**Comment by gauravs-JavaDeveloper** [comment]
Updated failing test case with appropriate expected message
